[package]
name = "yoursb-desktop"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rpassword = "7.2"
rand = "0.8.5"
dirs = "5.0"
arboard = "3.2.1"
walkdir = "2"
iced = "0.13.1"
yoursb-domain = { path = "../yoursb-domain" }
