import { VerticalBox, GroupBox, GridBox, HorizontalBox, TextEdit, Button, LineEdit, ScrollView } from "std-widgets.slint";
import { BigButton } from "components/home/big_button.slint";
import { Header } from "components/common/headbar.slint";
import { CategoryView, Category, EntryKind, Entry, Icon } from "components/home/category.slint";

export component HomeScreen inherits Window {
    in property <[[Category]]> Categories: [
        [
            {
                name: "Pinned",
                icon: Icon.Pin,
                content: [{
                    name: "Toto",
                    kind: EntryKind.FileDir,
                    name: "Google",
                    kind: EntryKind.PassDir,
                }],
            }
        ],
        [
            {
                name: "Passwords",
                icon: Icon.Pass,
                content: [{
                    name: "Google",
                    kind: EntryKind.PassDir,
                }, {
                    name: "Google",
                    kind: EntryKind.Pass,
                }],
            },
            {
                name: "Files",
                icon: Icon.File,
                content: [
                    {
                        name: "Toto89999991",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto2",
                        kind: EntryKind.File,
                    },
                    {
                        name: "Toto3",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto4",
                        kind: EntryKind.File,
                    },
                    {
                        name: "Toto5",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto6",
                        kind: EntryKind.File,
                    },
                    {
                        name: "Toto7",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto89999991",
                        kind: EntryKind.File,
                    },
                    {
                        name: "Toto9",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto10",
                        kind: EntryKind.File,
                    }
                ],
            }
        ],
    ];

    VerticalLayout {

        Header {
            width: 100%;
            height: 100px;
        }

        Rectangle {
            height: 3px;
            Rectangle {
                width: parent.width - 3.5rem;
                background: #585858;
                border-radius: parent.height;
            }
        }

        Rectangle {
            height: 1rem;
        }

        VerticalLayout {
            alignment: start;
            vertical-stretch: 1;
            spacing: 2rem;
            padding: 1rem;
            for category_line in Categories: HorizontalLayout {
                spacing: 1.5rem;
                for category in category-line: CategoryView {
                    content: category;
                }
            }
        }
    }
}

export component StartScreen inherits Window {
    in property <string> error_text: "";

    private property <bool> global_selected: false;
    private property <bool> local_selected: false;
    function select(global: bool) {
        global_selected = global;
        local_selected = !global;
    }
    callback open_instance(create: bool, global: bool, local_path: string);
    callback browse_files(string) -> string;
    title: "YourSB code Desktop";
    min-width: 500px;
    VerticalLayout {
        alignment: start;
        width: 500px;
        padding: 10px;
        spacing: 15px;
        Rectangle {
            Text {
                font-size: 30px;
                text: "YourSB Code";
                horizontal-alignment: center;
            }

            height: 50px;
            border-width: 3px;
            border-color: @linear-gradient(180deg, #FFFFFF00 99%, #FFFFFF50 100%, #FFFFFF50 100%);
        }

        Text {
            text: "Choose the instance to open:";
            font-size: 15px;
            height: 20px;
        }

        VerticalBox {
            BigButton {
                selected: global_selected;
                clicked => {
                    select(true)
                }
                VerticalLayout {
                    padding-top: 10px;
                    padding-bottom: 10px;
                    padding-left: 5px;
                    padding-right: 5px;
                    Text {
                        font-size: 16px;
                        text: "Global instance";
                        horizontal-alignment: center;
                    }
                }
            }

            BigButton {
                selected: local_selected;
                clicked => {
                    select(false)
                }
                VerticalLayout {
                    padding-top: 10px;
                    padding-bottom: 10px;
                    spacing: 5px;
                    Text {
                        font-size: 16px;
                        text: "Local instance";
                        horizontal-alignment: center;
                    }

                    HorizontalLayout {
                        padding: 10px;
                        spacing: 10px;
                        local_path := LineEdit {
                            edited(text) => {
                                select(false);
                            }
                            placeholder-text: "Instance path...";
                        }

                        Button {
                            text: "Browse...";
                            clicked => {
                                select(false);
                                local_path.text = browse_files(local_path.text);
                            }
                        }
                    }
                }
            }
        }

        if error_text != "": Text {
            text: error_text;
            horizontal-alignment: center;
            color: red;
            font-weight: 800;
            font-size: 1.2rem;
        }

        HorizontalLayout {
            spacing: 10px;
            Button {
                text: "Open";
                enabled: local_selected || global_selected;
                clicked => {
                    open_instance(false, global_selected, local_path.text);
                }
            }

            Button {
                text: "Create";
                enabled: local_selected || global_selected;
                clicked => {
                    open_instance(true, global_selected, local_path.text);
                }
            }
        }
    }
}
