import { VerticalBox, GroupBox, GridBox, HorizontalBox, TextEdit, Button, LineEdit, ScrollView } from "std-widgets.slint";
import { BigButton } from "components/home/big_button.slint";
import { Header } from "components/common/headbar.slint";

export enum EntryKind {
    PassDir,
    FileDir,
    Pass,
    File,
}

export struct Entry {
    name: string,
    kind: EntryKind,
}

export struct Category {
    name: string,
    icon: image,
    content: [Entry],
}

export component HomeScreen inherits Window {
    property <[[Category]]> Categories: [
        [
            {
                name: "Pinned",
                icon: @image-url("../../images/pin.svg"),
                content: [{
                    name: "Toto",
                    kind: EntryKind.FileDir,
                    name: "Google",
                    kind: EntryKind.PassDir,
                }],
            }
        ],
        [
            {
                name: "Passwords",
                icon: @image-url("../../images/pass.svg"),
                content: [{
                    name: "Google",
                    kind: EntryKind.PassDir,
                }, {
                    name: "Google",
                    kind: EntryKind.Pass,
                }],
            },
            {
                name: "Files",
                icon: @image-url("../../images/file.svg"),
                content: [
                    {
                        name: "Toto89999991",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto2",
                        kind: EntryKind.File,
                    },
                    {
                        name: "Toto3",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto4",
                        kind: EntryKind.File,
                    },
                    {
                        name: "Toto5",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto6",
                        kind: EntryKind.File,
                    },
                    {
                        name: "Toto7",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto89999991",
                        kind: EntryKind.File,
                    },
                    {
                        name: "Toto9",
                        kind: EntryKind.FileDir,
                    },
                    {
                        name: "Toto10",
                        kind: EntryKind.File,
                    }
                ],
            }
        ],
    ];

    pure function file-kind-image(kind: EntryKind) -> image {
        if kind == EntryKind.File {
            return @image-url("../../images/file.svg");
        } else if kind == EntryKind.Pass {
            return @image-url("../../images/pass.svg");
        } else if kind == EntryKind.FileDir {
            return @image-url("../../images/dir.svg");
        } else {
            return @image-url("../../images/dir.svg");
        }
    }

    VerticalLayout {

        Header {
            width: 100%;
            height: 100px;
        }

        Rectangle {
            height: 3px;
            Rectangle {
                width: parent.width - 3.5rem;
                background: #585858;
                border-radius: 1rem;
            }
        }

        Rectangle {
            height: 1rem;
        }

        VerticalLayout {
            alignment: start;
            vertical-stretch: 1;
            spacing: 2rem;
            padding: 1rem;
            for category_line in Categories: HorizontalLayout {
                spacing: 1.5rem;
                for category in category-line: Rectangle {
                    // Force equal size of each element
                    preferred-width: 1px;
                    min-width: 1px; // TODO: a higher value
                    horizontal-stretch: 1;

                    min-height: cat-body.min-height;
                    border-color: #585858;
                    border-width: 2px;
                    border-radius: 1.5rem;

                    cat-body := VerticalLayout {
                        width: 100%;
                        // preferred-height: scroll.preferred-height;
                        min-height: cat-header.height + inner.element-height + inner.padding-top + inner.padding-bottom;
                        height: parent.height;

                        cat-header := HorizontalLayout {
                            alignment: start;
                            padding-left: 1rem;
                            padding-right: 1rem;
                            padding-top: 0.3rem;
                            padding-bottom: 0rem;
                            spacing: 0.5rem;
                            height: self.preferred-height;
                            Image {
                                source: category.icon;
                                height: 3rem;
                                width: 3rem;
                            }

                            Rectangle {
                                Text {
                                    text: category.name;
                                    font-size: 1.4rem;
                                    font-weight: 500;
                                }
                            }
                        }

                        scroll := ScrollView {
                            preferred-height: inner.height;
                            viewport-width: self.width;
                            viewport-height: inner.height;
                            inner := Rectangle {
                                height: (nb-elems-height) * (element-height + spacing) + self.padding-top + self.padding-bottom - spacing;
                                
                                // Internal layout
                                private property <length> element-width: 9rem;
                                private property <length> element-height: 2rem;
                                private property <length> spacing: 1rem;
                                private property <int> nb-elems-width: floor((self.width - self.padding-left - self.padding-right + spacing) / (element-width + spacing));
                                private property <int> nb-elems-height: 1 + floor((category.content.length - 1) / nb-elems-width);
                                padding: 1.6rem;
                                padding-top: 1.6rem;
                                padding-bottom: 1.6rem;
                                padding-left: 1.6rem;
                                padding-right: 1.6rem;

                                for elem[i] in category.content: HorizontalLayout {
                                    x: parent.padding-left + mod(i, nb-elems-width) * (element-width + spacing);
                                    y: parent.padding-top + floor(i / nb-elems-width) * (element-height + spacing);
                                    width: element-width;
                                    height: element-height;
                                    spacing: 0.3rem;
                                    alignment: center;
                                    Image {
                                        source: root.file-kind-image(elem.kind);
                                        width: element-height;
                                    }

                                    Rectangle {
                                        Text {
                                            text: elem.name;
                                            font-weight: 500;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

export component StartScreen inherits Window {
    property <bool> global_selected: false;
    property <bool> local_selected: false;
    function select(global: bool) {
        global_selected = global;
        local_selected = !global;
    }
    callback submit(global: bool, local_path: string);
    callback browse_files(string) -> string;
    title: "YourSB code Desktop";
    min-width: 500px;
    min-height: 350px;
    VerticalLayout {
        width: 500px;
        height: 350px;
        padding: 10px;
        spacing: 15px;
        Rectangle {
            Text {
                font-size: 30px;
                text: "YourSB Code";
                horizontal-alignment: center;
            }

            height: 50px;
            border-width: 3px;
            border-color: @linear-gradient(180deg, #FFFFFF00 99%, #FFFFFF50 100%, #FFFFFF50 100%);
        }

        Text {
            text: "Choose the instance to open:";
            font-size: 15px;
            height: 20px;
        }

        VerticalBox {
            BigButton {
                selected: global_selected;
                clicked => {
                    select(true)
                }
                VerticalLayout {
                    padding-top: 10px;
                    padding-bottom: 10px;
                    padding-left: 5px;
                    padding-right: 5px;
                    Text {
                        font-size: 16px;
                        text: "Global instance";
                        horizontal-alignment: center;
                    }
                }
            }

            BigButton {
                selected: local_selected;
                clicked => {
                    select(false)
                }
                VerticalLayout {
                    padding-top: 10px;
                    padding-bottom: 10px;
                    spacing: 5px;
                    Text {
                        font-size: 16px;
                        text: "Local instance";
                        horizontal-alignment: center;
                    }

                    HorizontalLayout {
                        padding: 10px;
                        spacing: 10px;
                        local_path := LineEdit {
                            edited(text) => {
                                select(false);
                            }
                            placeholder-text: "Instance path...";
                        }

                        Button {
                            text: "Browse...";
                            clicked => {
                                select(false);
                                local_path.text = browse_files(local_path.text);
                            }
                        }
                    }
                }
            }
        }

        Button {
            text: "Open";
            enabled: local_selected || global_selected;
            clicked => {
                submit(global_selected, local_path.text);
            }
        }
    }
}
